config/routes.rb
Rails.application.routes.draw do
  
  resources :vehicles
  resources :vehicles do
    member do
      post 'sale', to: 'vehicles#buy'
    end
  end
  resources :sales
  devise_for :users
  # Set Views/Home/index is the main page
  root 'home#index'
  get 'home/index', to: 'home#index'
  
  get 'home/about'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/broker.rb
class Broker < ApplicationRecord

    has_many :sales
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :user
  belongs_to :broker
  belongs_to :vehicle
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :vehicles, dependent: :destroy
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :user
  has_many :sales, dependent: :nullify
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @sales = Sale.all
    @vehicles = Vehicle.all
    @users = User.all
    @brokers = Broker.all
  end
  def about
    @brokers = Broker.all
  end
  def contact
  end
  def faq
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # POST /sales
  # POST /sales.json
  def create
    
    @sale = Sale.new(sale_params)

    if @sale.save
      render :show, status: :created, location: @sale
    else
      render json: @sale.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    if @sale.update(sale_params)
      render :show, status: :ok, location: @sale
    else
      render json: @sale.errors, status: :unprocessable_entity
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:user_id, :vehicle_id, :broker_id)
    end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  
  before_action :set_vehicle, only: [:show, :edit, :update, :buy,:destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.all
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)
    @vehicle.user = current_user
    @vehicle.img_url = "car/0#{[1,2,3,4].sample}.jpg"
    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def buy
    @broker = Broker.all.sample
    @sale = Sale.create(
                    user: current_user,
                    broker: @broker,
                    vehicle: @vehicle)
    if @sale.save 
      redirect_to vehicles_url , notice: "Congrats, you just buyed a special fucking car"
      @vehicle.destroy
    end
             
        
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:user_id, :brand, :year, :model, :value)
    end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/home/about.html.erb
<!--======= INTRO SECTION  -->

 <section class="inner-intro bg-6 ">
  <div class="container">
     <div class="row text-center intro-title">
           <div class="col-lg-6 col-md-6 col-sm-6 text-left">
             <h1 class="text-white">About us </h1>
           </div>
           <div class="col-lg-6 col-md-6 col-sm-6 text-right">
             <ul class="page-breadcrumb">
                <li><a href="#"><i class="fa fa-home"></i> Home</a> <i class="fa fa-angle-double-right"></i></li>
                <li><a href="#">pages</a> <i class="fa fa-angle-double-right"></i></li>
                <li><span>About Us</span> </li>
             </ul>
        </div>
     </div>
  </div>
</section>
<!--======= INTRO SECTION  -->



<hr class="gray" />

<!--======= TESTMONIAL SECTION  -->

 <section class="testimonial-1 gray-new-bg  page page-section-ptb">
   <div class="container">
     <div class="row">
       <div class="col-lg-12 col-md-12">
         <div class="section-title">
           
           <h2>Brokers
           </h2>
           <div class="separator"></div>
         </div>
       </div>
     </div>
     <div class="row">
       <div class="col-lg-12 col-md-12">
         <div class="owl-carousel-2">
           <%@brokers.each do |b|%>
           <div class="item">
             <div class="testimonial-block text-center border-new">
               <div class="testimonial-image">

                 <%= image_tag(b.bg_img, :alt => "", :class => "img-responsive") %>

               </div>
               <div class="testimonial-box">
                 <div class="testimonial-avtar">
                   <%= image_tag(b.avatar, :alt => "", :class => "img-responsive") %>

                   <h6><%= b.name%></h6>
                   <span>Auto Dealer</span>
                 </div>
                 <div class="testimonial-content">
                   <p>It has survived not only five centuries. lorem Ipsum is simply dummy text of the printin a galley of type and bled it to make a type specimen book.</p>
                   <i class="fa fa-quote-right"></i>
                 </div>
               </div>
             </div>
           </div>
           <%end%>

           


       </div>
     </div>
   </div>
 </section>
<!--======= COUNTER SECTION  -->


<!--======= COUNTER SECTION  -->

<section class="counter counter-style-2 bg-red bg-1 bg-overlay-black-70 page-section-ptb">
  <div class="container">
    <div class="row">
     <div class="col-lg-3 col-md-3 col-sm-6 item">
     <div class="counter-block text-left">
        <div class="separator"></div>
        <div class="info">
           <h6 class="text-white">Vehicles in Stock</h6>
           <p><i class="fa fa-car"></i>
           <h3 class="text-white">550</h3></p>
         </div>
        </div>
     </div>
     <div class="col-lg-3 col-md-3 col-sm-6 item">
     <div class="counter-block text-left">
        <div class="separator"></div>
        <div class="info">
           <h6 class="text-white">Dealer Reviews</h6>
           <p>  <i class="fa fa-comments-o"></i></i>
           <h3 class="text-white">2500</h3></p>
         </div>
        </div>
     </div>
     <div class="col-lg-3 col-md-3 col-sm-6 item">
     <div class="counter-block text-left">
        <div class="separator"></div>
        <div class="info">
           <h6 class="text-white">Happy Customer</h6>
           <p><i class="fa fa-users"></i>
           <h3 class="text-white">10050</h3></p>
         </div>
        </div>
     </div>
      <div class="col-lg-3 col-md-3 col-sm-6 item">
      <div class="counter-block text-left">
        <div class="separator"></div>
        <div class="info">
           <h6 class="text-white">Awards</h6>
           <p><i class="fa fa-trophy"></i>
           <h3 class="text-white">350</h3></p>
         </div>
        </div>
     </div>
    </div>
  </div>
</section>

<!--======= COUNTER SECTION  -->

app/views/home/contact.html.erb
<!--======= INTRO  SECTION  -->

<section class="inner-intro bg-1 bg-overlay-black-70">
  <div class="container">
    <div class="row text-center intro-title">
      <div class="col-lg-6 col-md-6 col-sm-6 text-left">
        <h1 class="text-white">Conatct us </h1>
      </div>
      <div class="col-lg-6 col-md-6 col-sm-6 text-right">
        <ul class="page-breadcrumb">
          <li>
            <a href="#">
              <i class="fa fa-home"></i> Home</a>
            <i class="fa fa-angle-double-right"></i>
          </li>
          <li>
            <a href="#">pages</a>
            <i class="fa fa-angle-double-right"></i>
          </li>
          <li>
            <span>Conatct Us</span>
          </li>
        </ul>
      </div>
    </div>
  </div>
</section>
<!--======= INTRO  SECTION  -->

<!--======= CONTACT SECTION  -->

<section class="contact page-section-ptb gray-bg">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 col-md-12">
        <div class="section-title">
          <span>We’d Love to Hear From You</span>
          <h2>LET'S GET IN TOUCH!</h2>
          <div class="separator"></div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="contact-box text-center">
          <i class="fa fa-map-marker"></i>
          <h5>Address</h5>
          <p>220E Front St. Burlington NC 215</p>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="contact-box text-center">
          <i class="fa fa-phone"></i>
          <h5>Phone</h5>
          <p> (007) 123 456 7890</p>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="contact-box text-center">
          <i class="fa fa-envelope-o"></i>
          <h5>Email</h5>
          <p> support@website.com</p>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="contact-box text-center">
          <i class="fa fa-fax"></i>
          <h5>Fax</h5>
          <p>(007) 123 456 7890</p>
        </div>
      </div>
    </div>
    <div class="page-section-ptb">
      <div class="row">
        <div class="col-lg-8 col-md-8">
          <div class="gray-form row">
            <div id="formmessage">Success/Error Message Goes Here</div>
            <form class="form-horizontal" id="contactform" role="form" method="post" action="php/contact-form.php">
              <div class="contact-form">
                <div class="col-lg-4 col-md-4">
                  <div class="form-group">
                    <input id="name" type="text" placeholder="Name*" class="form-control" name="name">
                  </div>
                </div>
                <div class="col-lg-4 col-md-4">
                  <div class="form-group">
                    <input type="email" placeholder="Email*" class="form-control" name="email">
                  </div>
                </div>
                <div class="col-lg-4 col-md-4">
                  <div class="form-group">
                    <input type="text" placeholder="Phone*" class="form-control" name="phone">
                  </div>
                </div>
                <div class="col-lg-12 col-md-12">
                  <div class="form-group">
                    <textarea class="form-control input-message" placeholder="Comment*" rows="7" name="message"></textarea>
                  </div>
                </div>
                <div class="col-lg-4 col-md-4 col-md-offset-4">
                  <input type="hidden" name="action" value="sendEmail" />
                  <button id="submit" name="submit" type="submit" value="Send" class="button red"> Send your message </button>
                </div>
              </div>
            </form>
            <div id="ajaxloader" style="display:none">
              <img class="center-block" src="images/ajax-loader.gif" alt="">
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-md-4">
          <div class="opening-hours gray-bg">
            <h6>opening hours</h6>
            <ul class="list-style-none">
              <li>
                <strong>Sunday</strong>
                <span class="text-red"> closed</span>
              </li>
              <li>
                <strong>Monday</strong>
                <span> 9:00 AM to 9:00 PM</span>
              </li>
              <li>
                <strong>Tuesday </strong>
                <span> 9:00 AM to 9:00 PM</span>
              </li>
              <li>
                <strong>Wednesday </strong>
                <span> 9:00 AM to 9:00 PM</span>
              </li>
              <li>
                <strong>Thursday </strong>
                <span> 9:00 AM to 9:00 PM</span>
              </li>
              <li>
                <strong>Friday </strong>
                <span> 9:00 AM to 9:00 PM</span>
              </li>
              <li>
                <strong>Saturday </strong>
                <span> 9:00 AM to 9:00 PM</span>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-4 col-md-4 col-sm-4">
        <div class="feature-box-3">
          <div class="icon">
            <i class="fa fa-clock-o"></i>
          </div>
          <div class="content">
            <h6>opening hours </h6>
            <p>Voluptatem accusanoremque sed ut perspiciatis unde omnis iste natus error sit laudantium, totam rem aperiam.
              </p>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-4">
        <div class="feature-box-3">
          <div class="icon">
            <i class="fa fa-support"></i>
          </div>
          <div class="content">
            <h6>Our Support Center </h6>
            <p>Iste natus error sit sed ut perspiciatis unde omnis voluptatem laudantium, totam rem aperiam. </p>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-4">
        <div class="feature-box-3">
          <div class="icon">
            <i class="fa fa-info"></i>
          </div>
          <div class="content">
            <h6>Some Information </h6>
            <p>Totam rem aperiam sed ut perspiciatis unde omnis iste natus error sit voluptatem laudantium.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<!--======= CONTACT SECTION  -->


<!--======= CONTACT MAP SECTION  -->

<section class="contact-map">
  <div class="container-fluid">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3224.017231421863!2d-79.43780268425046!3d36.09306798010035!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x88532bae09664ccb%3A0xaa6b8f98d3fb8135!2s220+E+Front+St%2C+Burlington%2C+NC+27215%2C+USA!5e0!3m2!1sen!2sin!4v1475045272926"
      allowfullscreen></iframe>
  </div>
</section>

<!--======= CONTACT MAP SECTION  -->

app/views/home/faq.html.erb
<!--======= INTRO  SECTION  -->

<section class="inner-intro bg-7 bg-overlay-black-70">
  <div class="container">
    <div class="row text-center intro-title">
      <div class="col-lg-6 col-md-6 text-left">
        <h1 class="text-white">Faq</h1>
      </div>
      <div class="col-lg-6 col-md-6 text-right">
        <ul class="page-breadcrumb">
          <li>
            <a href="#">
              <i class="fa fa-home"></i> Home</a>
            <i class="fa fa-angle-double-right"></i>
          </li>
          <li>
            <a href="#">pages</a>
            <i class="fa fa-angle-double-right"></i>
          </li>
          <li>
            <span>FAQ</span>
          </li>
        </ul>
      </div>
    </div>
  </div>
</section>

<!--======= INTRO  SECTION  -->

app/views/layouts/_navigation.html.erb
<!--================================= Loading -->
<div id="loading">
  <div id="loading-center">
    <%= image_tag('loader.gif', :alt => "") %>
  </div>
</div>
<!--================================= Loading -->

<!--================================= Header  -->
<header id="header" class="defualt">
  <div class="menu">
    <nav id="menu" class="mega-menu">
      <section class="menu-list-items">
        <div class="container">
          <div class="row">
            <div class="col-lg-12 col-md-12">
              <ul class="menu-logo">
                <li>
                    <%= image_tag('logo-light.png', :alt => "logo", :class => "img-responsive") %></a>
                <div class="menu-mobile-collapse-trigger"><span></span></div></li>
              </ul>
              <ul class="menu-links">
                <li class="active">
                  <%= link_to 'Home', home_index_path %>
                </li>
                <li>
                  <%= link_to 'About Us', home_about_path %>
                </li>
                <li>
                  <%= link_to 'Vehicles', vehicles_path %>
                </li>
                <li>
                <%if user_signed_in?%> 
                  <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
                <%else%>
                  <%= link_to 'Sign in', new_user_session_path %>
                <%end%>	
                </li>
              </ul>
            </div>
          </div>
        </div>
      </section>
    </nav>
  </div>
</header>
<!--================================= Header -->

app/views/layouts/devise.html.erb
<%= stylesheet_link_tag    'devise', media: 'all', 'data-turbolinks-track': 'reload' %>
<div class="wrapper fadeInDown">
  <div id="formContent"> 
    <%=yield%>

  </div>
</div>

app/views/sales/edit.html.erb
<h1>Editing Sale</h1>

<%= render 'form', sale: @sale %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sales</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= link_to 'Show', sale %></td>
        <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
        <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sale', new_sale_path %>

app/views/sales/new.html.erb
<h1>New Sale</h1>

<%= render 'form', sale: @sale %>

<%= link_to 'Back', sales_path %>

app/views/sales/show.html.erb
 <section class="inner-intro bg-6 ">
  <div class="container">
     <div class="row text-center intro-title">
           <div class="col-lg-6 col-md-6 col-sm-6 text-left">
             <h1 class="text-white">Sales </h1>
           </div>
           <div class="col-lg-6 col-md-6 col-sm-6 text-right">
             <ul class="page-breadcrumb">
                <li><a href="#"><i class="fa fa-home"></i> Home</a> <i class="fa fa-angle-double-right"></i></li>
                <li><a href="#">pages</a> <i class="fa fa-angle-double-right"></i></li>
                <li><span>Sales</span> </li>
             </ul>
        </div>
     </div>
  </div>
</section>

<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>

app/views/users/shared/_links.html.erb
<div id="formFooter">
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) ,class:"underlineHover"%><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) ,class:"underlineHover"%><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) ,class:"underlineHover"%><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) ,class:"underlineHover"%><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) ,class:"underlineHover"%><br />
  <% end %>
<% end %>
</div> 

app/views/vehicles/edit.html.erb
<section class="inner-intro bg-7 bg-overlay-black-70">
  <div class="container">
    <div class="row text-center intro-title">
      <div class="col-lg-6 col-md-6 text-left">
        <h1 class="text-white">Vehicles</h1>
      </div>
      <div class="col-lg-6 col-md-6 text-right">
        <ul class="page-breadcrumb">
          <li>
            <a href="#">
              <i class="fa fa-home"></i> Home</a>
            <i class="fa fa-angle-double-right"></i>
          </li>
          <li>
            <a href="#">pages</a>
            <i class="fa fa-angle-double-right"></i>
          </li>
          <li>
            <span>Vehicles</span>
          </li>
        </ul>
      </div>
    </div>
  </div>
</section>

<h1>Editing Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>

app/views/vehicles/index.html.erb
<section class="inner-intro bg-7 bg-overlay-black-70">
  <div class="container">
    <div class="row text-center intro-title">
      <div class="col-lg-6 col-md-6 text-left">
         <h1 class="text-white">Vehicles</h1>
        <%if user_signed_in?%>
        <%= link_to new_vehicle_path do %>
        <i class="fa fa-plus" style="font-size:45px;"></i>
        <%end%>
        <%end%>
      </div>
      <div class="col-lg-6 col-md-6 text-right">
        <ul class="page-breadcrumb">
          <li>
            <a href="#">
              <i class="fa fa-home"></i> Home</a>
            <i class="fa fa-angle-double-right"></i>
          </li>
          <li>
            <a href="#">pages</a>
            <i class="fa fa-angle-double-right"></i>
          </li>
          <li>
            <span>Vehicles</span>
          </li>
        </ul>
      </div>
    </div>
  </div>
</section>

<br>
<br>


<!--===== FEATURE CAR SECTION -->

    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12">
                <div class="owl-carousel-1">
                    
                <%@vehicles.each do |car| %>    
                    <div class="item">
                        <div class="car-item text-center">
                            <div class="car-image">
                                <%=image_tag (car.img_url), class:"img-responsive", alt:"" %>
                                    <div class="car-overlay-banner">
                                      <ul>
                                        <li>
                                        <%= link_to(car) do %>
                                        <i class="fa fa-link">
                                        </i>
                                        <%end%>
                                        </li>
                                        <li><a href="#"><i class="fa fa-dashboard"></i></a></li>
                                      </ul>
                                    </div>
                            </div>
                            <div class="car-list">
                                <ul class="list-inline">
                                    <li><i class="fa fa-registered"></i> <%= car.year%></li>
                                    <li><i class="fa fa-cog"></i> Manual</li>
                                    <li><i class="fa fa-dashboard"></i> 6,000 mi</li>
                                </ul>
                            </div>
                            <div class="car-content">
                                <div class="star">
                                    <i class="fa fa-star orange-color"></i>
                                    <i class="fa fa-star orange-color"></i>
                                    <i class="fa fa-star orange-color"></i>
                                    <i class="fa fa-star orange-color"></i>
                                    <i class="fa fa-star-o orange-color"></i>
                                </div>
                                <a href="#"><%= "#{car.brand}  #{car.model}"%></a>
                                <div class="separator"></div>
                                <div class="price">
                                    <span class="old-price">$<%= car.value %></span>
                                    <span class="new-price">$<%= car.value %></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <%end%>

                </div>
            </div>
        </div>
    </div>

<!--===== FEATURE CAR SECTION -->










<%
=begin%>
 <table>
  <thead>
    <tr>
      <th>User</th>
      <th>Brand</th>
      <th>Year</th>
      <th>Model</th>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= vehicle.user %></td>
        <td><%= vehicle.brand %></td>
        <td><%= vehicle.year %></td>
        <td><%= vehicle.model %></td>
        <td><%= vehicle.value %></td>
        <td><%= link_to 'Show', vehicle %></td>
        <td><%= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
        <td><%= link_to 'Destroy', vehicle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vehicle', new_vehicle_path %> 
<%
=end%>




</div>

app/views/vehicles/show.html.erb
<section class="inner-intro bg-1 bg-overlay-black-70">
  <div class="container">
    <div class="row text-center intro-title">
      <div class="col-lg-6 col-md-6 text-left">
        <h1 class="text-white">Vehicles</h1>
      </div>
      <div class="col-lg-6 col-md-6 text-right">
        <ul class="page-breadcrumb">
          <li>
            <a href="#">
              <i class="fa fa-home"></i> Home</a>
            <i class="fa fa-angle-double-right"></i>
          </li>
          <li>
            <a href="#">pages</a>
            <i class="fa fa-angle-double-right"></i>
          </li>
          <li>
            <span>Vehicles</span>
          </li>
        </ul>
      </div>
    </div>
  </div>
</section>


<div class="col-lg-12 col-md-12">
        <div class="section-title">
        <br>
          <span>Your new</span>
          <h2> <%="#{@vehicle.brand } #{@vehicle.model}"%>
          </h2>
          <div class="separator"></div>
        </div>
      </div>

<div class="custom-block-1">
      <div class="text-center">
        <div class="col-lg-6 col-md-6 col-sm-6">
          <div class="blog-content">
                      <h2><%="#{@vehicle.model}"%></h2>
          <span>Get the <%="#{@vehicle.brand } #{@vehicle.model}"%> You always Wanted </span>
          <strong class="text-red"><%="$#{@vehicle.value}"%> </strong>
          <span>Only </span>
          <p>Limited time Offer!</p>
          <%if user_signed_in? && current_user != @vehicle.user%>
          
          <%= button_to  "BUY ME", sale_vehicle_path, class:"button border"%>
          <%else%>
          <span style='color: red;'>Sign in, to buy </span>
          <%end%> 
          </div>
        </div>
         <div class="col-lg-6 col-md-6 col-sm-6">
          <%= image_tag  @vehicle.img_url, class:"img-responsive" %>

        </div>
      </div>
    </div>


     <div class="col-lg-12 col-md-12">
        <div class="section-title">
          <br><br><br>       
           <div class="separator"></div>
        </div>
      </div>










<%= link_to 'Back', vehicles_path %>